[package]
name = "rustpager"
version = "0.4.0"
authors = ["Thomas Gatzweiler <mail@thomasgatzweiler.com>"]

[dependencies]
log = "^0.3"
serial = "^0.3"
ws = "^0.6"
tiny_http = "^0.5.7"
serde = "^0.9"
serde_derive = "^0.9"
serde_json = "^0.9"
lazy_static = "^0.2.2"
net2 = "^0.2.26"

[dependencies.raspi]
path = "lib/raspi"
